"""Add module support and relationships

Revision ID: dba8b83432a4
Revises: 93ce50fced83
Create Date: 2025-07-17 14:45:02.216563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba8b83432a4'
down_revision: Union[str, None] = '93ce50fced83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'modules', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='unique')
    # ### end Alembic commands ###